#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(r32f, binding = 0) uniform image2D imgOutput;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    vec4 currentColor = imageLoad(imgOutput, texelCoord);
    if (currentColor.r > 0.0)
    {
        imageStore(imgOutput, texelCoord, vec4(1.0));
    }
    else
    {
        imageStore(imgOutput, texelCoord, vec4(0.0));
    }
}
